### ISSUE TITLE
store multiple theme names (light and dark) in the settings

### ISSUE THREAD

**Issue by zacharyburnett** [bimlas/xfce4-night-mode#1]
for instance, these are all light / dark themes:
```
adwaita
adwaita-dark
``` 
```
Matcha-azul
Matcha-dark-azul
``` 
```
Papirus
Papirus-Dark
```
perhaps the settings can store the names of  light and dark themes separately

**Comment by Saijin-Naib** [comment]
This would be great for me, and something I was going to open an issue for.

My GTK themes are:  
Adwaita
Adwaita-dark

My Icon themes are:  
Numix
Numix Light

My Cursor themes are:  
Numix-Cursor
Numix-Cursor-Light

So in my case with Numix assets, only the GTK theme switches properly on schedule (Adwaita), but my cursor and icon themes do not.

**Comment by harmtemolder** [comment]
The original code only handles cases where the light theme doesn't have a suffix, and the dark theme `-dark` as suffix. @zacharyburnett forked it and added an option to specify the suffix for dark mode, to handle `-Dark`, for example. But there is no option yet to handle `Matcha-azul` vs. `Matcha-dark-azul` or `Numix` vs. `Numix Light`. I'll go see if I can add fields to `night-mode` in the Settings Editor to explicitly specify what themes to use

**Comment by harmtemolder** [comment]
OK, looks like that works: #3

**Comment by bimlas** [comment]
Solved, thanks to @harmtemolder
