### ISSUE TITLE
Feature Request: Manage XFWM4 themes

### ISSUE THREAD

**Issue by Saijin-Naib** [bimlas/xfce4-night-mode#4]
Using Themix/Oomox, I created a theme based upon Arc with both light and dark variants. I also was able to generate/export XFWM4 themes of both styles. I noticed that xfce4-night-mode does not appear to manage XFWM4 themes like it does GTK/icon/cursor themes.

Would it be possible to add this functionality?

**Comment by bimlas** [comment]
I think #3 solved the problem, please update the script and check if works now. Please be sure to set up the theme names first (see the latest README: https://github.com/bimlas/xfce4-night-mode#settings)

**Comment by Saijin-Naib** [comment]
Works amazingly well!
Light:  
![image](https://user-images.githubusercontent.com/19295950/160918619-26892c97-4e5e-416f-8030-db41dfb76f93.png)
Dark:  
![image](https://user-images.githubusercontent.com/19295950/160918692-da0d57e2-4661-4e12-b97e-a11474ee7838.png)
